http:
    middlewares:
        redirect-to-https:
            redirectScheme:
                scheme: https

        hsts-headers:
            headers:
                frameDeny: true
                browserXssFilter: true
                contentTypeNosniff: true
                customFrameOptionsValue: SAMEORIGIN
                accessControlAllowMethods:
                    - GET
                    - OPTIONS
                    - PUT
                accessControlMaxAge: 100
                addVaryHeader: true
                forceSTSHeader: true
                stsIncludeSubdomains: true
                stsPreload: true
                stsSeconds: 63072000

tls:
    stores:
        default:
            defaultCertificate:
                certFile: /etc/ssl/traefik/cert.pem
                keyFile: /etc/ssl/traefik/privkey.pem
    certificates:
        - certFile: /etc/ssl/traefik/cert.pem
          keyFile: /etc/ssl/traefik/privkey.pem
    options:
        intermediate:
            minVersion: VersionTLS12
            cipherSuites:
                - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 # TLS 1.2
                - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305  # TLS 1.2
                - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384   # TLS 1.2
                - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305    # TLS 1.2
                - TLS_AES_256_GCM_SHA384                  # TLS 1.3
                - TLS_CHACHA20_POLY1305_SHA256            # TLS 1.3
                - TLS_FALLBACK_SCSV                       # TLS FALLBACK
            curvePreferences:
                - CurveP521
                - CurveP384
            sniStrict: true
        modern:
            minVersion: VersionTLS13
