logLevel: INFO

api:
    dashboard: true
    debug: true

entryPoints:
    web:
        address: ":80"
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https

    websecure:
        address: ":443"
        http:
            tls:
                options: intermediate@file

providers:
    file:
        filename: /etc/traefik/provider.yml
    docker:
        endpoint: unix:///var/run/docker.sock
        watch: true
        exposedByDefault: false
        defaultRule: "HostRegexp(`{{ index .Labels \"com.docker.compose.service\"}}.traefik.me`,`{{ index .Labels \"com.docker.compose.service\"}}-{dashed-ip:.*}.traefik.me`)"
